version: '3.3'

services:
  advertisement:
    build: ./advertisements
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./advertisements/:/app/
    ports:
      - 8001:8000
    environment:
      - USERS_SERVICE_HOST_URL=http://users:8000/
      - RELATIONS_SERVICE_HOST_URL=http://relations:8000/
      - DATABASE_URI=postgresql://advertisement_db_username:advertisement_db_password@advertisement_db/advertisement_db_dev
    depends_on:
      - user_db

  advertisement_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_advertisement:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=advertisement_db_username
      - POSTGRES_PASSWORD=advertisement_db_password
      - POSTGRES_DB=advertisement_db_dev

  users:
    build: ./users
    command: uvicorn api:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./users/:/app/
    ports:
      - 8002:8000
    environment:
      - ADVERTISEMENTS_SERVICE_HOST_URL=http://advertisements:8000/
      - DATABASE_URI=postgresql://user_db_username:user_db_password@user_db/user_db_dev
      - RELATIONS_SERVICE_HOST_URL=http://relations:8000/
    depends_on:
      - user_db

  user_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_user:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user_db_username
      - POSTGRES_PASSWORD=user_db_password
      - POSTGRES_DB=user_db_dev
  
  relations:
    build: ./relations
    command: uvicorn api:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./relations/:/app/
    ports:
      - 8003:8000
    environment:
      - DATABASE_URI=postgresql://relation_db_username:relation_db_password@relation_db/relation_db_dev
      - USERS_SERVICE_HOST_URL=http://users:8000/
      - ADVERTISEMENTS_SERVICE_HOST_URL=http://advertisements:8000/
    depends_on:
      - relation_db

  relation_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_relation:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=relation_db_username
      - POSTGRES_PASSWORD=relation_db_password
      - POSTGRES_DB=relation_db_dev

volumes:
  postgres_data_user:
  postgres_data_relation:
  postgres_data_advertisement: